name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "checkout the current branch"
        uses: actions/checkout@v4
      - name: "set up golang"
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: "Build the binary"
        run: make build
      - name: "Run unit tests"
        run: make test-coverage
      - name: "Run integration tests"
        run: make test-integration
      - name: "check test coverage"
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: coverage.out
          git-token:
            ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
      - name: "Archive code coverage results"
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.out

  code_coverage:
    name: "Code coverage report"
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - name: "checkout the current branch"
        uses: actions/checkout@v4
      - uses: fgrosse/go-coverage-report@v1.2.0
        with:
          coverage-file-name: "coverage.out"
